export { default as card } from './card'
export { default as footer } from './footer'
export { default as headline } from './headline'
export { default as headlineSpan } from './headline-span'
export { default as links } from './links'
export { default as linksGroup } from './links-group'
export { default as main } from './main'
export { default as page } from './page'
